### ISSUE TITLE
Error: Module did not self-register.

### ISSUE THREAD

**Issue by babsonmatt** [ncb000gt/node.bcrypt.js#281] opened 2015-03-16 03:05 UTC
I receive this error while attempting to run my app via nodemon/forever/etc.

I'm running on win 7 x64 with iojs 1.5.1

Everything works fine if I run without the above tools.

**Comment by defunctzombie** [comment] 2015-03-16 06:27
duplicate of #280

**Closed by defunctzombie** 2015-03-16 06:27 UTC

**Comment by babsonmatt** [comment] 2015-03-16 16:07
Not sure if this is a duplicate as I'm able to use the library just fine... except when trying to run my app via nodemon/forever etc.

**Comment by defunctzombie** [comment] 2015-03-16 16:25
That is an issue to take up with nodemon or forever. If it runs fine otherwise I would first start with whatever those libs are trying to do.

**Comment by babsonmatt** [comment] 2015-03-16 17:32
I'll give that a go, thanks for your time
